version: '3.7'

x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  image: sasaplus1/setup
  init: true
  volumes:
    - .:/mnt

services:
  sh:
    <<: *base
    command:
      - bash
    tty: true
  test:
    <<: *base
    command:
      - make setup
