.DEFAULT_GOAL := all

SHELL := /bin/bash

makefile := $(abspath $(lastword $(MAKEFILE_LIST)))
makefile_dir := $(dir $(makefile))

root := $(makefile_dir)

ghq ?= ghq

.PHONY: all
all: ## output targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(makefile) | awk 'BEGIN { FS = ":.*?## " }; { printf "\033[36m%-30s\033[0m %s\n", $$1, $$2 }'

.PHONY: setup
setup: repositories := $(root)/repositories.txt
setup: ## install repositories
	xargs -n 1 $(ghq) get --update < '$(repositories)'

.PHONY: maintenance
maintenance: setup ## maintenance repositories
