name: lint workflows

on:
  push:
    paths:
      - '.github/workflows/*'

jobs:
  lint-workflow-files:
    name: lint workflow files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: docker://rhysd/actionlint:latest
