name: test

on:
  push:
  pull_request:
  schedule:
    # NOTE: at 8:05 am everyday by JST
    - cron: '5 23 * * *'

jobs:
  macos:
    name: setup macOS
    if: >
      github.event_name == 'push'
      || github.event_name == 'schedule'
      || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - run: curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      - run: source ./macports-ci install
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: make setup
        env:
          GH_TOKEN: ${{ github.token }}
  ubuntu:
    name: setup Ubuntu
    if: >
      github.event_name == 'push'
      || github.event_name == 'schedule'
      || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    env:
      LANG: C
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: make setup
        env:
          GH_TOKEN: ${{ github.token }}
