name: test

on:
  push:
  pull_request:
  schedule:
    # NOTE: at 8:05 am everyday by JST
    - cron: '5 23 * * *'

jobs:
  macos-ports:
    name: install MacPorts
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: macOS-latest
    steps:
      - run: curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      - run: source ./macports-ci install
      - uses: actions/checkout@v2
      - run: make install-ports
  ubuntu-apt:
    name: install APT packages
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    env:
      LANG: C
    steps:
      - uses: actions/checkout@v2
      - run: make install-apt-packages
  on-macos:
    name: setup macOS
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: make setup
  on-ubuntu:
    name: setup Ubuntu
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    env:
      LANG: C
    steps:
      - uses: actions/checkout@v2
      - run: make setup
