name: test

on:
  push:
  pull_request:
  schedule:
    # NOTE: at 8:05 am everyday by JST
    - cron: '5 23 * * *'

jobs:
  on-macos:
    name: macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: make setup
      - run: ./bash && "$HOME/Local/bin/bash" --version
  on-ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    env:
      LANG: C
    steps:
      - uses: actions/checkout@v2
      - run: make setup
      - run: ./bash && "$HOME/Local/bin/bash" --version
