name: test

on:
  push:
  pull_request:
  schedule:
    # NOTE: at 8:05 am everyday by JST
    - cron: '5 23 * * *'

jobs:
  nix:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-env --version
      - run: nix-env --help
      - run: nix-env -e hello
      - run: hello

  macos-ports:
    name: install MacPorts
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - run: curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      - run: source ./macports-ci install
      - uses: actions/checkout@v4
      - run: make install-ports
  ubuntu-apt:
    name: install APT packages
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    env:
      LANG: C
    steps:
      - uses: actions/checkout@v4
      - run: make install-apt-packages
  on-macos:
    name: setup macOS
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: make setup
  on-ubuntu:
    name: setup Ubuntu
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    env:
      LANG: C
    steps:
      - uses: actions/checkout@v4
      - run: make setup
